const popularProducts = [
    {
      id: 1,
      title: "Seeds of Change Organic Red Rice",
      category: "Fresh Fruit",
      brand: "NestFood",
      price: 28.85,
      oldPrice: 32.80,
      discount: 13,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 2,
      title: "All Natural Style Chicken Meatballs",
      category: "Bread and Juice",
      brand: "NestFood",
      price: 52.85,
      oldPrice: 55.80,
      discount: 6,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 3,
      title: "Angie's Sweet & Salty Kettle Corn",
      category: "Baking material",
      brand: "Country Crock",
      price: 48.85,
      oldPrice: 52.80,
      discount: 8,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 4,
      title: "Foster Farms Takeout Crispy Classic",
      category: "Baking material",
      brand: "Country Crock",
      price: 17.85,
      oldPrice: 19.80,
      discount: 10,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 5,
      title: "Blue Almonds Lightly Salted Vegetables",
      category: "Fresh Fruit",
      brand: "Country Crock",
      price: 23.85,
      oldPrice: 25.80,
      discount: 8,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 6,
      title: "Chobani Complete Vanilla Greek Yogurt",
      category: "Fresh Fruit",
      brand: "Country Crock",
      price: 54.85,
      oldPrice: 55.80,
      discount: 2,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 7,
      title: "Häagen-Dazs Caramel Cone Ice Cream Boxed",
      category: "Baking material",
      brand: "Hambger Hel",
      price: 22.85,
      oldPrice: 24.80,
      discount: 8,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 8,
      title: "Gorton’s Beer Battered Fish Fillets",
      category: "Fresh Seafood",
      brand: "Hambger Hel",
      price: 23.85,
      oldPrice: 25.80,
      discount: 8,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 9,
      title: "Encore Seafoods Stuffed Alaskan",
      category: "Clothing & beauty",
      brand: "Hambger Hel",
      price: 35.85,
      oldPrice: 37.80,
      discount: 6,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 10,
      title: "Canada Dry Ginger Ale – 2 L Bottle",
      category: "Baking material",
      brand: "Hambger Hel",
      price: 32.85,
      oldPrice: 35.80,
      discount: 3,
      rating: 4,
      image: "/public/product1.svg",
    },
    {
      id: 11,
      title: "Extra Virgin Olive Oil, Canola Oil, Nonfat",
      category: "Baking material",
      brand: "Totino's Pizza",
      price: 58.00,
      oldPrice: 60.00,
      discount: 4,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 12,
      title: "Frozen Vegetables Broccoli, Spinach",
      category: "Baking material",
      brand: "Totino's Pizza",
      price: 71.00,
      oldPrice: 75.00,
      discount: 6,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 13,
      title: "Frozen Fruit Strawberry, Berries",
      category: "Fresh Fruit",
      brand: "Maruchan Ramen",
      price: 78.00,
      oldPrice: 98.00,
      discount: 21,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 14,
      title: "Pre-portioned, Low-fat Ice Cream Yogurt",
      category: "Bread and Juice",
      brand: "Maruchan Ramen",
      price: 79.00,
      oldPrice: 99.00,
      discount: 21,
      rating: 4,
      image: "/public/product.svg",
    },
    {
      id: 15,
      title: "Dried Fruit: Apricots, Figs, Prunes",
      category: "Baking material",
      brand: "USA Noodle Soup",
      price: 56.00,
      oldPrice: 76.00,
      discount: 27,
      rating: 5,
      image: "/public/product.svg",
    },
  ];
  
  export default popularProducts;